"""Reply generation controller using Gemini.

Uses Gemini API when configured, and safely falls back to an empty reply so
API contract is always honored.
"""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.parse
import urllib.request

from dotenv import load_dotenv


load_dotenv()

GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta"
DEFAULT_GEMINI_MODEL = "gemini-2.0-flash"
FALLBACK_MODELS = ("gemini-2.0-flash", "gemini-2.5-flash")


def _debug_enabled() -> bool:
    return os.getenv("HONEYPOT_LLM_DEBUG", "false").strip().lower() in {"1", "true", "yes", "on"}


def _debug_log(message: str) -> None:
    if _debug_enabled():
        print(f"[GeminiDebug] {message}")


def _resolve_api_key() -> str:
    """Support canonical and commonly mistyped env var names."""
    return (
        os.getenv("GEMINI_API_KEY", "").strip()
        or os.getenv("Gemini_API_Key", "").strip()
    )


def _build_prompt(conversation_history: list[dict], latest_message: dict) -> str:
    lines = [
        (
            "You are a normal human user chatting with someone who may be a scammer. "
            "Reply naturally, briefly, and contextually. "
            "Do not reveal that you are detecting scams or running any analysis."
        ),
        "",
        "Conversation so far:",
    ]

    for item in conversation_history:
        sender = item.get("sender", "unknown")
        text = str(item.get("text", "")).strip()
        if text:
            lines.append(f"{sender}: {text}")

    latest_sender = latest_message.get("sender", "scammer")
    latest_text = str(latest_message.get("text", "")).strip()
    if latest_text:
        lines.append(f"{latest_sender}: {latest_text}")

    lines.extend([
        "",
        "Write only the next user message reply as plain text.",
    ])
    return "\n".join(lines)


def _call_gemini(*, model: str, api_key: str, prompt: str) -> str:
    url = f"{GEMINI_API_BASE}/models/{urllib.parse.quote(model)}:generateContent?key={urllib.parse.quote(api_key)}"
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": 0.7,
            "maxOutputTokens": 120,
        },
    }

    request = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    with urllib.request.urlopen(request, timeout=10) as response:
        raw = response.read().decode("utf-8", errors="replace")
        data = json.loads(raw)
        candidates = data.get("candidates", [])
        if not candidates:
            _debug_log(f"No candidates from model={model}: {raw[:300]}")
            return ""

        parts = candidates[0].get("content", {}).get("parts", [])
        text_chunks = [part.get("text", "") for part in parts if isinstance(part, dict)]
        reply = "\n".join(chunk for chunk in text_chunks if chunk).strip()
        if not reply:
            _debug_log(f"Empty reply from model={model}; parts={json.dumps(parts)[:300]}")
        return reply


def generate_reply(conversation_history: list[dict], latest_message: dict) -> str:
    """Return a human-like reply string.

    Falls back to empty string if model config is unavailable or call fails.
    """
    api_key = _resolve_api_key()
    if not api_key:
        _debug_log("Missing GEMINI_API_KEY (or Gemini_API_Key)")
        return ""

    configured_model = os.getenv("HONEYPOT_CHAT_MODEL", DEFAULT_GEMINI_MODEL).strip() or DEFAULT_GEMINI_MODEL
    prompt = _build_prompt(conversation_history, latest_message)

    models_to_try = [configured_model]
    for fallback in FALLBACK_MODELS:
        if fallback not in models_to_try:
            models_to_try.append(fallback)

    for model in models_to_try:
        try:
            _debug_log(f"Calling Gemini model={model}")
            reply = _call_gemini(model=model, api_key=api_key, prompt=prompt)
            if reply:
                _debug_log(f"Reply generated by model={model}")
                return reply
        except urllib.error.HTTPError as exc:
            error_body = exc.read().decode("utf-8", errors="replace")
            _debug_log(f"HTTPError model={model} code={exc.code}: {error_body[:300]}")
            # Retry with next model only for model-not-found or quota/rate limits.
            if exc.code not in (404, 429):
                return ""
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as exc:
            _debug_log(f"Request error model={model}: {exc}")
            return ""

    return ""
